import json

# Company data
companies = [
    {"id": 17, "name": "Micorosft", "industry": "Technology", "location": "Nairobi,Kenya"},
    {"id": 1, "name": "Eaagads Ltd.", "industry": "Agricultural", "location": "Kigali, Rwanda"},
    {"id": 1, "name": "Kapchorua Tea Kenya Plc.", "industry": "Agricultural", "location": "Nairobi, Kenya"},
    {"id": 1, "name": "Kakuzi Plc", "industry": "Agricultural", "location": "Abuja, Nigeria"},
    {"id": 1, "name": "Limuru Tea Co. Ltd.", "industry": "Agricultural", "location": "Kampala, Uganda"},
    {"id": 1, "name": "Sasini Plc.", "industry": "Agricultural", "location": "Kigali, Rwanda"},
    {"id": 1, "name": "Williamson Tea Kenya Plc.", "industry": "Agricultural", "location": "Nairobi, Kenya"},
    {"id": 16, "name": "Car & General (K) Ltd.", "industry": "Automobile and accessories", "location": "Nairobi, Kenya"},
    {"id": 4, "name": "ABSA Bank Kenya Plc.", "industry": "Financial services", "location": "Nairobi, Kenya"},
    {"id": 4, "name": "I&M Bank", "industry": "Financial services", "location": "Kigali, Rwanda"},
    {"id": 4, "name": "Bank of Kigali", "industry": "Financial services", "location": "Kigali, Rwanda"},
    {"id": 4, "name": "Jumia group", "industry": "Financial services", "location": "Lagos, Nigeria"},
    {"id": 15, "name": "Andela", "industry": "Commercial and professional services", "location": "New York, United States"},
    {"id": 13, "name": "Takealot", "industry": "E-commerce and retail", "location": "Cape Town, South Africa"},
    {"id": 10, "name": "Zola Electric", "industry": "Energy and Environment Resources", "location": "Arusha, Tanzania"},
    {"id": 10, "name": "D.light", "industry": "Energy and resources", "location": "San Fransisco, United Sates of America"},
    {"id": 10, "name": "Rwanda Energy Group", "industry": "Energy and resources", "location": "Kigali, Rwanda"},
    {"id": 14, "name": "Swvl", "industry": "Transport and logistics", "location": "Cairo, Egypt"},
    {"id": 14, "name": "Winer logistic campany", "industry": "Transport and logistics", "location": "Kigali, Rwanda"},
    {"id": 14, "name": "Right travel&Safaris agency", "industry": "Transport and logistics", "location": "Kigali, Rwanda"},
    {"id": 13, "name": "Konga", "industry": "E-commerce and retail", "location": "Lagos, Nigeria"},
    {"id": 11, "name": "Jumo", "industry": "Financial services", "location": "Cape Town, South Africa"},
    {"id": 10, "name": "M-kopa", "industry": "Energy and environment resources", "location": "Nairobi, Kenya"},
    {"id": 11, "name": "Cellulant", "industry": "Financial services", "location": "Nairobi, Kenya"},
    {"id": 12, "name": "African Leadership Academy", "industry": "Education", "location": "Cape Town, South Africa"},
    {"id": 12, "name": "African Leadership University", "industry": "Education", "location": "Kigali, Rwanda"},
    {"id": 12, "name": "University of Rwanda", "industry": "Education", "location": "Kigali, Rwanda"},
    {"id": 11, "name": "Opay", "industry": "Financial services", "location": "Lagos, Nigeria"},
    {"id": 11, "name": "CarePay", "industry": "Financial services", "location": "Nairobi, Kenya"},
    {"id": 10, "name": "Powerhive", "industry": "Energy and environment resources", "location": "Nairobi, Kenya"},
    {"id": 9, "name": "Travelstart", "industry": "Travel and leisure", "location": "Cape Town, South Africa"},
    {"id": 8, "name": "Nabaki Afrika", "industry": "Construction and Real Estate", "location": "Dar es Salaam, Tanzania"},
    {"id": 8, "name": "Addis Property Marketing Group", "industry": "Construction and Real Estate", "location": "Addis Ababa, Ethiopia"},
    {"id": 7, "name": "Artniom", "industry": "Health and beauty", "location": "Abuja, Nigeria"},
    {"id": 1, "name": "Seminis East Africa", "industry": "Agricultural", "location": "Nairobi, Kenya"},
    {"id": 1, "name": "Floranet", "industry": "Agricultural", "location": "Nairobi, Kenya"},
    {"id": 1, "name": "Agribiz", "industry": "Agricultural", "location": "Ilupeju, Nigeria"},
    {"id": 1, "name": "Agriquip Agencies", "industry": "Agricultural", "location": "Nairobi, Kenya"},
    {"id": 6, "name": "Guludo Beach Lodge", "industry": "Hotels, Lodges and Toursim", "location": "Guludo, Mozambique"},
    {"id": 6, "name": "Lake Kariba", "industry": "Hotels, Lodges and Tourism", "location": "Lake Kariba, Zambia"},
    {"id": 6, "name": "Bulago", "industry": "Hotels, Lodges and Tourism", "location": "Kampala, Uganda"},
    {"id": 6, "name": "Kaingu Safari Lounge", "industry": "Hotels, Lodges and Tourism", "location": "Lusaka, Zambia"},
    {"id": 6, "name": "Boma Hotel", "industry": "Hotels, Lodges and Tourism", "location": "Entebbe, Uganda"},
    {"id": 5, "name": "Veroniach and Miencha Advocates", "industry": "Services", "location": "Nairobi, Kenya"},
    {"id": 5, "name": "General Maintenance", "industry": "Services", "location": "Baie Du Tombeau, Mauritius"},
    {"id": 5, "name": "Starffor Global", "industry": "Services", "location": "Port Louis, Mauritius"},
    {"id": 5, "name": "Magnate Venture Ltd", "industry": "Services", "location": "Nairobi, Kenya"},
    {"id": 4, "name": "Africa Furniture Importers Directory", "industry": "Home and Office Furniture", "location": "Africa, United Arab Emirates"},
    {"id": 4, "name": "Magari", "industry": "Home and Office Furniture", "location": "Nairobi, Kenya"},
    {"id": 4, "name": "Home decor", "industry": "Home and Office Furniture", "location": "Kigali, Rwanda"},
    {"id": 4, "name": "Hwan Sung Ltd", "industry": "Home and Furniture", "location": "Kampala, Uganda"},
    {"id": 4, "name": "Antarc Enterprises Ltd", "industry": "Home and Furniture", "location": "Nairobi, Kenya"},
    {"id": 2, "name": "Elephant Group Limited", "industry": "Electronics and Electrical", "location": "Lagos, Nigeria"},
    {"id": 2, "name": "Arrow Altech Distribution", "industry": "Electronics and Electrical", "location": "Milnerton, South Africa"},
    {"id": 2, "name": "GAM Solar Energy and Engineering Co. Ltd", "industry": "Electronics and Electrical", "location": "Serrekunda, Gambia"},
    {"id": 3, "name": "BAJ Trading Ltd.", "industry": "Foodstuff and Beverages", "location":"Nairobi, Kenya"},
    {"id": 3, "name": "Camellia", "industry": "Foodstuff and Beverages", "location":"Kigali, Rwanda"},
    {"id": 3, "name": "Ireland Blyth", "industry": "Foodstuff and Beverages", "location": "Port Louis, Mauritius"}
]

# Writing to JSON file
with open('companies.json', 'w') as json_file:
    json.dump(companies, json_file, indent=2)
